---
# Options
simp_options::dns::servers: ['8.8.8.8']
simp_options::puppet::server: puppet
simp_options::puppet::ca: puppet
simp_options::ntpd::servers: ['time.nist.gov']
simp_options::ldap::bind_pw: 's00per sekr3t!'
simp_options::ldap::bind_hash: '{SSHA}foobarbaz!!!!'
simp_options::ldap::sync_pw: 's00per sekr3t!'
simp_options::ldap::sync_hash: '{SSHA}foobarbaz!!!!'
simp_options::ldap::root_hash: '{SSHA}foobarbaz!!!!'
simp_options::auditd: true
simp_options::haveged: true
simp_options::pam: true
simp_options::logrotate: true
simp_options::selinux: true
simp_options::tcpwrappers: true
simp_options::firewall: true

# simp_options::log_servers: ['#{master_fqdn}']
sssd::domains: ['LOCAL']
simp::yum::servers: ['puppet']

# Settings required for acceptance test, some may be required
simp::scenario: simp
simp_options::rsync: false
simp_options::clamav: false
simp_options::pki: true
simp_options::pki::source: '/etc/pki/simp-testing/pki'
simp_options::trusted_nets: ['ALL']
simp::yum::os_update_url: http://mirror.centos.org/centos/$releasever/os/$basearch/
simp::yum::enable_simp_repos: false
pupmod::enable_puppet_master: true

# Settings to make beaker happy
sudo::user_specifications:
  vagrant_all:
    user_list: ['vagrant']
    cmnd: ['ALL']
    passwd: false
pam::access::users:
  defaults:
    origins:
      - ALL
    permission: '+'
  vagrant:
ssh::server::conf::permitrootlogin: true
ssh::server::conf::authorizedkeysfile: .ssh/authorized_keys
